apiVersion: v1
kind: PersistentVolume # how to specify the type of manifest
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # or block are two different types of storage    
  storageClassName: standard # type `kubectl get sc` to get the name
  accessModes: # - details https://kubernetes.io/docs/concepts/storage/persistent-volumes/
    # all three can be claimed, but only one at a time. Because we use a hostPath
    # we only will have a single node
    - ReadWriteOnce # means this volume can be claimed by a single node (but multiple pods)
   
    # Two other options, see url above for documentation
    # - ReadOnlyMany
    # - ReadWriteMany 
  hostPath:
    path: /data
    type: DirectoryOrCreate
  